builds:
- goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  - "386"
  env:
  - CGO_ENABLED=0

archives:
- format: binary
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

# vim: set et ts=2 sw=2:
